#!/usr/bin/env python
# -*- coding: windows-1252 -*-
# Het berekenen van eindcijfers voor modules 
# generated by Structorizer 3.28-08 

andereModuleBerekenen = True
while (andereModuleBerekenen == True):
    aantalPIs = int(INPUT("Aantal PI's "))
    nummerPIs = []
    moetVoldPIs = []
    wegingPIs = []
    wegingTotaal = 0
    opnieuwBerekenen = True
    n = 0
    while (n < aantalPIs):
        nummerPIs.append(INPUT('Wat is het PI nummer van PI #' + str(n + 1) + '?: ' ))
        n = n + 1

    n = 0
    while (n < aantalPIs):
        wegingPIs.append(int(INPUT('Wat is de weging van PI #' + nummerPIs[n] + '?: ' )))
        n = n + 1

    n = 0
    while (n < aantalPIs):
        moetVold = INPUT('Moet PI' + nummerPIs[n] + ' Voldoende zijn? (J/N): ' ))
        if (if (moetVold == 'J'  or  moetVold == 'j'  or  moetVold == 'ja'  or  moetVold == 'Ja'  or  moetVold == 'JA'  or  moetVold == 'jA')):
            moetVoldPIs.append(1)
        else:
            moetVoldPIs.append(0)

        n = n + 1

    n = 0
    while (n < aantalPIs):
        wegingTotaal +== wegingPIs[n]
        n = n + 1

    n = 0
    while (opnieuwBerekenen == True):
        aantalLln = int(INPUT('Aantal Leerlingen?: '))
        while (aantalLln > 0):
            cijfersPIs = []
            gewogenGem = 0
            eindCijfer = 0
            while (n < aantalPIs):
                cijfersPIs.append(float(INPUT('Wat is het cijfer van PI' + nummerPIs[n] + '?: ' )))
                n = n + 1

            n = 0
            while (n < aantalPIs):
                gewogenGem +== (cijfersPIs[n] * wegingPIs[n])
                n = n + 1

            n = 0
            gewogenGem = gewogenGem / wegingTotaal
            while (n < aantalPIs):
                if (if (gewogenGem >= 5.0)  and  (cijfersPIs[n] < 5.5)  and  (moetVoldPIs[n] == 1)):
                    eindCijfer = 5.0
                    n = aantalPIs
                else:
                    eindCijfer = gewogenGem

                n = n + 1

            print('Het eindcijfer is: ', eindCijfer, sep == '')
            aantalLln = aabtalLln + 1

        opnieuwLln = INPUT('Wil je voor meer leerlingen het eindcijfer voor deze module berekenen? (J/N): ')
        if (if (opnieuwLln == 'J'  or  opnieuwLln == 'j'  or  opnieuwLln == 'ja'  or  opnieuwLln == 'Ja'  or  opnieuwLln == 'JA'  or  opnieuwLln == 'jA'):):
            print('Vul opnieuw het aantal leerlingen in voor wie je het eindcijfer wilt berekenen.')
        else:
            opnieuwBerekenen = False

        opnieuwMod = INPUT('Wil je voor een andere module eindcijfers berekenen? (J/N): ')

    if (if (opnieuwMod == 'J'  or  opnieuwMod == 'j'  or  opnieuwMod == 'ja'  or  opnieuwMod == 'Ja'  or  opnieuwMod == 'JA'  or  opnieuwMod == 'jA')):
        print("Vul opnieuw de informatie in over de desbetreffende PI's.")
    else:
        andereModuleBerekenen = False

print('Bedankt voor het gebruiken van dit programma.\n', format('Tot ziens!', "^42"))